- name: create new file
  file:
     path: "/root/ip.txt"
     mode: 0644
     state: file
  become: yes

- name: get IP
  ipify_facts:
  become: yes

- name: set ip
  copy:
    dest: "/root/ip.txt"
    content: |
      {{ ipify_public_ip }}
  become: yes