tasks:
  - name: Install epel-release
    yum:
        name: epel-release
        state: present

  - name: Install Nginx
    yum:
        name: nginx
        state: latest
     notify: Start Nginx

  - name: Install Git
    yum:
       name: git
       state: latest

handlers:
  - name: Start Nginx
    service:
            name=nginx
            state=started
            enabled=True
