  - name: Install epel-release
    yum:
       name: epel-release
       state: latest
    become: yes

  - name: Install Nginx
    yum:
        name: nginx
        state: latest
    become: yes

  - name: Install Git
    yum:
        name: git
        state: latest
    become: yes

  - name: Start Nginx
    service:
        name=nginx
        state=started
    become: yes
