  - name: Install epel-release
    yum:
       name: epel-release
       state: latest
    become: yes

  - name: Install Nginx
    yum:
        name: nginx
        state: latest
    become: yes

  - name: Install Git
    yum:
        name: git
        state: latest
    become: yes

  - name: Start Nginx
    service:
        name=nginx
        state=started
    become: yes

  - name: copy nginx.conf to host
    copy:
      src: ../file/nginx.conf
      dest: /etc/nginx/conf.d/
    become: yes

  - name: get IP
    ipify_facts:
    become: yes

  - name: set IP Address
    replace:
      path: /etc/nginx/conf.d/nginx.conf
      regexp: 'ip_address'
      replace: "{{ ipify_public_ip }}"
    become: yes


  - name: make dir
    file:
      path: /home/centos/nginx/html
      state: directory
    become: yes

  - name: copy nginx.conf to host
    copy:
      src: ../file/index.html
      dest: /home/centos/nginx/html
    become: yes
