  - name: Install epel-release
    yum:
       name: epel-release
       state: latest
    become: yes

  - name: Install Nginx
    yum:
        name: nginx
        state: latest
    become: yes

  - name: Install Git
    yum:
        name: git
        state: latest
    become: yes

  - name: Start Nginx
    service:
        name=nginx
        state=started
    become: yes

  - name: copy nginx.conf to host
    copy:
      src: ../file/nginx.conf
      dest: /etc/nginx/conf.d/
    become: yes

  - name: set ip
    command: sed -i 's/ip_address/"{{ item.public_ip }}"/g' /etc/nginx/conf.d/nginx.conf
    become: yes

  - name: make dir
    file:
      path: /home/centos/nginx/html
    become: yes
