- include_vars: "instance.yml"

- name: Create Instance
  ec2:
    aws_access_key: "{{ access }}"
    aws_secret_key: "{{ secret }}"
    region: "{{ region }}"
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    wait: yes
    group: "{{ group }}"
    count: "{{ count }}"
    vpc_subnet_id: "{{ subnet_id }}"
    assign_public_ip: yes
    instance_tags:
       name: project
       owner: ansible
    volumes:
     - device_name: /dev/sda1
       volume_type: gp2
       volume_size: 8
       delete_on_termination: yes
  register: ec2_out
