# - name: Setting up Security/Firewall Group
#   import_tasks: setting_up_firewall.yml

- name: Provision an EC2 Instances
  import_tasks: create_ec2_instance.yml

- name: Add all instance public IPs to host group
  add_host: hostname={{ item.public_ip }} groups=aws_hosts
  with_items: "{{ ec2_out.instances }}"

- name: create file
  file:
    path: /root/instanceId.txt
    mode: 0644
    state: touch

  become: yes

- name: set instanceID
  copy:
    dest: /root/instanceId.txt
    content: |
      {{ item.id }}
  with_items: "{{ ec2_out.instances }}"
  become: yes

- name: Wait for ssh to come
  wait_for: host={{ item.public_dns_name }} port=22 delay=30 timeout=320 state=started 
  with_items: "{{ ec2_out.instances }}"
