- ec2_group:
    name: Transcend
    description: Allowing port 22 and 80
    region: ap-southeast-1
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 8080
        to_port: 8080
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 10050
        to_port: 10050
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 10051
        to_port: 10051
        cidr_ip: 0.0.0.0/0


    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
