---
- name: Import Zabbix RPM Key 
  shell: sudo rpm -i https://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm

- name: Install Zabbix
  yum: name={{item}} state=present
  with_items:
      - "zabbix-server-mysql"
      - "zabbix-web-mysql"
      - "zabbix-agent"
  becom: yes

- name: copy installation.sh 
  copy:
    src: /root/transcend-api/ansible/roles/install_zabbix/tasks/files/zabbix.sh
    dest: /root/
  become: yes

#- name: Create a new database with name 'zabbix'
#  mysql_db:
#    name: zabbix
#    encoding: utf8
#    collation: utf8_bin
#    state: present

- name: Create initial database
  shell: sudo sh /root/zabbix.sh

- name: Init Zabbix Server Mariadb Database
  expect: 
    command: /bin/bash -c "zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -uzabbix -p zabbix"
    responses:
        (?i)Password: 'transcend'
  becom: yes
