---
- name: Import Zabbix RPM Key 
  shell: sudo rpm -i https://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm

- name: Install Zabbix
  yum: name={{item}} state=present
  with_items:
      - "zabbix-server-mysql"
      - "zabbix-web-mysql"
      - "zabbix-agent"
      - "mysql-python"
  become: yes

- name: Create a new database with name 'zabbix'
  mysql_db:
    name: zabbix
    encoding: utf8
    collation: utf8_bin
    state: present

- mysql_user:
    name: 'zabbix'
    password: 'zabbix'
    priv: 'zabbix.*:ALL'
    host: localhost
    state: present


- name: Init Zabbix Server Mariadb Database
  expect: 
    command: /bin/bash -c "zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -uzabbix -p zabbix"
    responses:
        (?i)Password: 'transcend'
  become: yes

- name: set IP Address
  replace:
      path: /etc/zabbix/zabbix_server.conf
      regexp: '#DBPassword='
      replace: 'DBPassword=transcend'
  become: yes

- name: set timezone
  replace:
      path: /etc/httpd/conf.d/zabbix.conf
      regexp: '#php_value date.timezone Europe/Riga'
      replace: 'php_value date.timezone Asia/Bangkok'
  become: yes
  
- name: Start and enable zabbix
  shell: systemctl start zabbix-server zabbix-agent httpd | systemctl enable zabbix-server zabbix-agent httpd