---
- name: Import Zabbix RPM Key 
  rpm_key: state=present key="http://repo.zabbix.com/RPM-GPG-KEY-ZABBIX"
 
- name: Get Zabbix RPM
  yum: name="http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm" state=present

- name: Install Zabbix
  yum: name={{item}} state=present
  with_items:
      - "zabbix-server"
      - "zabbix-agent"

- name: Install python expect
  pip:
    name: pexpect

- name: Init Zabbix Server Mariadb Database
  expect: 
    command: /bin/bash -c "zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -uzabbix -p zabbix"
    responses:
        (?i)Password: 'zabbix'
