---
- name: Install MariaDB
  shell: sudo yum install -y mariadb-server

- name: Start and enable service
  service: 
    name: mariadb 
    state: started  
    enabled: yes

- name: mysql_secure_installation
  shell: bash /root/transcend/ansible/roles/install_zabbix/files/installation.sh