---
- name: Import Zabbix RPM Key 
  shell: sudo rpm -ivh https://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-2.el7.noarch.rpm

- name: Install Zabbix
  yum: name={{item}} state=present
  with_items:
      - "zabbix-server-mysql"
      - "zabbix-web-mysql"
      - "zabbix-proxy-mysql"
      - "zabbix-agent"
      - "epel-release"
  become: yes

- name: Install mysql-python
  shell: sudo yum install -y MySQL-python

- name: Install pip
  include: install_pip.yml

- name: Install pexpect
  shell: pip install pexpect

- name: Create a new database with name 'zabbix'
  mysql_db:
    login_user: 'root'
    login_password: 'transcend'
    name: zabbix
    encoding: utf8
    collation: utf8_bin
    state: present

- mysql_user:
    login_user: 'root'
    login_password: 'transcend'
    name: 'zabbix'
    password: 'transcend'
    priv: 'zabbix.*:ALL'
    host: localhost
    state: present

- name: Init Zabbix Server Mariadb Database
  expect: 
    command: /bin/bash -c "zcat /usr/share/doc/zabbix-server-mysql*/create.sql.gz | mysql -uzabbix -p zabbix"
    responses:
        (?i)Password: 'transcend'
  become: yes

- name: set IP Address
  replace:
      path: /etc/zabbix/zabbix_server.conf
      regexp: '# DBPassword='
      replace: 'DBPassword=transcend'
  become: yes

- name: set timezone
  replace:
      path: /etc/httpd/conf.d/zabbix.conf
      regexp: '# php_value date.timezone Europe/Riga'
      replace: 'php_value date.timezone Asia/Bangkok'
  become: yes
  
- name: Start and enable zabbix
  shell: systemctl start zabbix-server zabbix-agent httpd | systemctl enable zabbix-server zabbix-agent httpd

- name: Add firewall 10050 and 10051
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    with_items:
      - "http"
      - "https"

- name: Add firewall port
  firewalld:
    port: 10050-10051/tcp
    permanent: true
    state: enabled

- name: SELinux configuration
  shell: setsebool -P httpd_can_connect_zabbix on | setsebool -P httpd_can_network_connect_db on | setsebool -P httpd_can_network_connect on | setsebool -P zabbix_can_network on
  