---
- name: Install MariaDB
  yum: name={{ item }} state=present
  with_items:
    - MariaDB-server

- name: Install MySQLdb Python package for secure installations.
  yum: name=MySQL-python state=present