- name: Install mariadb
  yum:
    name: mariadb-server
    state: present

- name: Install the Python MySQL Support Libraries
  yum: pkg=MySQL-python state=latest

- name: start mysql server and enable it on reboot
  service: name=mariadb state=started enabled=true

- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "zabbix"
    login_user: zabbix
    login_password: "zabbix"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy the root credentials as .my.cnf file
  template: src=root.cnf.j2 dest=~/.my.cnf mode=0600
