---
- hosts: local
  connection: local
  gather_facts: no
  tasks:
      - name: Create a new EC2 key
        ec2_key:
            name: project
            region: ap-southeast-1
        register: ec2_key_result

      - name: Save private key
        copy: content="{{ ec2_key_result.key.private_key }}" dest="/root/project.pem" mode=0600
        when: ec2_key_result.changed

      - name: Wait for ssh to come
        wait_for: 
          port: 22 
          delay: 60 
          state: started 

