---
- hosts: local
  user: root
  connection: local
  gather_facts: false
  roles:
    - initial_ec2

- hosts: aws_hosts
  gather_facts: false
  user: centos
  vars_files:
    - /root/transcend-api/ansible/vars/software.yml
    - /root/transcend-api/ansible/vars/instance.yml
  tasks: 
    - import_role:
        name: 'install_{{ software }}'

    - import_role:
        name: import_IP

    # - import_role:
    #     name: install_zabbix
    #   when: '"{{ monitor }}" == "zabbix"'

    # - import_role:
    #     name: install_gitLab
    #   when: '"{{ code }}" == "gitlab"'