---
- hosts: local
  user: root
  connection: local
  gather_facts: false
  vars_files:
    - /root/transcend-api/ansible/vars/terminate.yml
  tasks:
  - name: terminate ec2 instance
    ec2:
      instance_ids: '{{ instanceId }}'
      region: ap-southeast-1
      state: 'absent'